name: firebase_login_auth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4 
  cloud_firestore: ^5.6.8 
  google_fonts: ^6.2.1
  sizer: ^2.0.15
  transformable_list_view: ^0.7.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true 
  ios: true
  web: true
  
  image_path: "assets/images/logo.png"

flutter_native_splash:
  android: true
  ios: true
  web: false

 
  color: "#ffffff"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
